### ISSUE TITLE
Known Issues v4.1

### ISSUE THREAD

**Issue by shantigilbert** [EmuELEC/EmuELEC#577]
### Fixed in Dev:    
- [x] Brightness is not saved correctly on boot (OGA/OGS/GF) (#574)
- [x] Some ports do not have background music e.g. VVVVVV & HCL
- [x] Shader issues
- [x] Two timezone menus in system settings (#572)

### Not yet fixed

**Amlogic-ng**
- [ ] Dolphin needs automatic gamepad configuration (#576)

**Odroid Go Advance/Super**
- [ ] Kernel panic (or other random issues, like waking up from sleep) maybe caused by some WiFi dongles (Realtek RTL8188CUS)

### Under investigation but not yet confirmed
* Some gamepads do not work with the kill command and error logs

**Comment by bennington111** [comment]
Black screen if use Swanstation core on x96 mini (s905w) 2/16. Sound is ok, but black screen.

**Comment by PikachuEXE** [comment]
https://github.com/EmuELEC/EmuELEC/issues/589
This issue is fixed in dev, but not tested yet

**Comment by iCanuck** [comment]
Do you have rough idea when dolphin auto gamepad config will be added? Thanks for all your work.

**Comment by leonkiss** [comment]
start 4.1  Display the overscan screen ，can't do anything. how to fix it?

**Comment by SamuEDL** [comment]
> 
> 
> start 4.1 Display the overscan screen ，can't do anything. how to fix it?

Some televisions allow to deactivate the "overscan". Check if possible in yours.
